### ISSUE TITLE
インポスターがタスクを処理する場合

### ISSUE THREAD

**Issue by yokmama** [ryokno08/werewolfGame#51]
インポスターがたすくを処理する場合、見かけ上アーマスタンドをそこにおくのか？
それとも、タスクを処理しているようにみせる必要はないか？

また、タスクを処理するように見せかけるためアーマースタンドを起き、テレポートしたならば、そのインポスtがーはどうやったら部屋からでられるのか？

**Comment by ryosuke0818** [comment]
インポスターはタスク場所にテレポートせず、その場でスペクテイターになります。フェイクタスクをしている状態でキルすることはできないため、フェイクタスクを解いてからキルする必要があります。
